Add styles for rows in user table
ghernandez345/fleet pull request #2
Opened 2021-04-02 23:18 UTC by noahtalerman

- Add status indicators for the new "Users" table
- Make "Actions" dropdown display above the table

2021-04-06 09:16 UTC, ghernandez345 requested changes

2021-04-06 09:16 UTC, ghernandez345 commented on frontend/components/TableContainer/DataTable/_styles.scss
> +      &--online, &--active {
hey lets change this implementation and move these styles out of this file. DataTable is a generic table that shows the data it is passed. It has no concept of what `offline` `online` and `invite pending` are. Let's try to move these into the `_styles.scss` files of  `ManageHostPage` and `UserManagementPage` respectively, as that is where those statuses have more of a meaning.

2021-04-06 09:16 UTC, ghernandez345 commented on frontend/components/TableContainer/DataTable/StatusCell/StatusCell.tsx
> +  const generateClassTag = (rawValue: string) => {
Lets be explicit on the return value type. Out linting will throw a warning without it. so this should be:

```javascript
const generateClassTag = (rawValue: string): string => {}
```

2021-04-06 09:16 UTC, ghernandez345 commented on frontend/components/forms/fields/Dropdown/_styles.scss
> +    padding: 10px;
we can improve this if we use the scss variables if possible

2021-04-06 09:16 UTC, ghernandez345 commented on frontend/components/TableContainer/DataTable/DropdownCell/_styles.scss
> +    border-radius: 4px;
there is a scss variable for border radiuses (is it radii???) i think.

2021-04-06 16:53 UTC, noahtalerman commented on frontend/components/TableContainer/DataTable/StatusCell/StatusCell.tsx
> +  const generateClassTag = (rawValue: string) => {
Got it. Ty for the typescript guidance.

2021-04-07 00:40 UTC, noahtalerman commented
@ghernandez345 my latest commits refactor the data table styles by eliminating duplicate and unused styles from `UserManagementPage` and `ManageHostsPage`
- Move status styles to respective stylesheets for `UserManagementPage` and `ManageHostsPage`
- Add return type for `GenerateClassTag()`
- Add scss variables in `Dropdown`. I also made minor updates to these values. More changes to variables are to come with the Aligning Figma components with Fleet UI project (fleetdm/fleet/issues/539)
- Add border-radius variable

2021-04-07 09:41 UTC, ghernandez345 commented on frontend/pages/admin/UserManagementPage/_styles.scss
> -  &__wrapper {
nice thanks for cleaning up

2021-04-07 09:41 UTC, ghernandez345 approved these changes

2021-04-07 09:41 UTC, merged